# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{robot_rules}
  s.version = "0.9.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Edward Gray II", "Jeremy Friesen", "Edgar Gonzalez"]
  s.date = %q{2010-07-21}
  s.email = %q{edgargonzalez@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "lib/robot_rules.rb",
     "robot_rules.gemspec",
     "test/robot_rules_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/hasmanydevelopers/robot_rules}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A tool to determine if the robots.txt would prevent a given user agent from making a request to a given URI.}
  s.test_files = [
    "test/test_helper.rb",
     "test/robot_rules_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 2.1.2"])
    else
      s.add_dependency(%q<addressable>, [">= 2.1.2"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 2.1.2"])
  end
end

